### ISSUE TITLE
Bättre presentation av externa dataset

### ISSUE THREAD

**Issue by peterk** [Kungbib/data.kb.se#11]
Dataset som distribuerats via t.ex. Commons ser inte så bra ut (se t.ex: [Tessins resedagbok](https://data.kb.se/datasets/Nicodemus%20Tessin%20Resedagbok%201687-1688) )

Sidan behöver städas upp och metadata kanske måste hanteras på ett annat sätt.

**Comment by sterutkb** [comment]
Vad tycks?

Ska länk texten vara Se även kanske? Eller ta bort det fältet helt och hållet om path saknas, och istället vissa länken i beskrivningstexten?

**Comment by peterk** [comment]
Ser ingen ändring? URL?
