### ISSUE TITLE
UTF-8-kodade filnamn kan inte laddas ner

### ISSUE THREAD

**Issue by peterk** [Kungbib/data.kb.se#19]
Vår version av flask (0.10.1) har trasig implementering av utf-8-kodade filnamn. Uppgradera flask till 0.12.2 eller senare bör lösa problemet.

Eftersom OSX har specialhantering av filnamn kan man tillbringa lång tid med felsökning om man inte normaliserar directory listning i /lib/dataDB.py runt rad 103 så här:

```
files = [unicodedata.normalize('NFC', f) for f in listdir(path.join(datasetRoot, directory))]
   for f in files:
```

**Comment by marma** [comment]
Lösningen, for future reference, var att

* lägga till miljövariabler för Apache så att Python accepterar icke-ASCII-tecken i filnamn (för os.path.join, basename, etc.)
* inte skicka filer som attachment, det fungerar bara med ASCII-filnamn.
* skicka filnamnet till send_file som en UTF-8-kodad bytestring, inte Unicode.
