### ISSUE TITLE
Automatisk uppdatering av självbeskrivande datamängder

### ISSUE THREAD

**Issue by marma** [Kungbib/data.kb.se#3]
Som medarbetare vill jag slippa att uppdatera information om datamängder som exempelvis via VoID själva kan göra detta.

**Comment by niklasl** [comment]
Example: use the data at <bibdb.libris.kb.se/.well-known/void> to seed the record for BibDB.

**Comment by sterutkb** [comment]
Going through issues and came across this one.

Is this still relevant? What exactly is the problem being described?
