### ISSUE TITLE
Footloose

### ISSUE THREAD

**Issue by klngwll** [Kungbib/data.kb.se#4]
På 
https://data.kb.se/datasets/Auktoritetsdata och 
https://data.kb.se/datasets/Nationalbibliografin
breakar footern

**Comment by oBlissing** [comment]
http://getbootstrap.com/examples/sticky-footer/ kanske är till hjälp?

**Comment by sterutkb** [comment]
Problemet var en felaktig {% endif %} i dataset template (container blev endast stängt då det var filer)
