### ISSUE TITLE
Absoluta länkar i identifierare för dataset

### ISSUE THREAD

**Issue by peterk** [Kungbib/data.kb.se#6]
```xml
<dcat:Dataset rdf:about="/datasets/2014/10/aftonbladet/">
```
borde vara:

```xml
<dcat:Dataset rdf:about="https://data.kb.se/datasets/2014/10/aftonbladet/">
```

...för att kedjan till öppnadata.se -> europeandataportal.eu ska bli intakt. Se:

http://xn--ppnadata-m4a.se/dataset/aftonbladet-1831-1862

och http://www.europeandataportal.eu/data/en/dataset/aftonbladet-1831-1862

**Comment by niklasl** [comment]
Är det ett krav i DCAT-AP att länkar ska vara fulla, eller bara en bugg i öppnadata.se? För i RDF (liksom för hyperlänkar generellt) ska slash-länkar resolvas mot basen på dokumentet.

(Jag accepterar att vi måste fixa detta för att komma runt fel i konsumtionskedjan (en lätt fix), men det måste rapporteras tillbaks så att det inte drabbar andra som publicerar data. Att kräva RDF/XML är olyckligt begränsande i sig, att inte konsumera den korrekt är ännu värre...)

**Comment by peterk** [comment]
Inget krav, men verktygskedjan är paj verkar det som. Pragmatisk fix just nu.

**Comment by niklasl** [comment]
OK. Jag har gjort fixen på develop, så den kommer väl med i nästa release?
