### ISSUE TITLE
Ange ett ämnesområde via dcat theme för alla dataset

### ISSUE THREAD

**Issue by peterk** [Kungbib/data.kb.se#7]
Skapa möjligheter att få 

```xml
<dcat:themeTaxonomy rdf:resource="http://eurovoc.europa.eu/"/>
```
...på datakatlognivån och lägg till följande (ämnesområde "vetenskap") som default i alla dataset:

```xml
<dcat:theme rdf:resource="http://eurovoc.europa.eu/100151"/>
```
Se dokumentation här:
https://docs.google.com/document/d/1A7OUPTqWIvKGdaArOORIJKlowFynA0UWBO1M4BnE4Ak/edit

**Comment by peterk** [comment]
Fixad i feature branch dcat-various

**Comment by sterutkb** [comment]
Fixed in commit https://github.com/Kungbib/data.kb.se/commit/93c41a19e37d0137045c413c4bc365cfc4804585

Merged with develop branch.
